"""Add sum model

Revision ID: 0bc28f6d8905
Revises: 
Create Date: 2024-03-17 13:29:49.199733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc28f6d8905'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sum_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__sum_results'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sum_results')
    # ### end Alembic commands ###
